### Description:
There are *2N* people a company is planning to interview.   
The cost of flying the i-th person to city A is costs[i][0], 
and the cost of flying the i-th person to city B is costs[i][1].

Return the minimum cost to fly every person to a city such that exactly N people arrive in each city.

* Example 1
Input: [[10,20],[30,200],[400,50],[30,20]]  

|Num| Data | Choice A|Choice B|  
|:---:|:--|:---:|:---:| 
|1|[10,20]|10|~~20~~|
|2|[30,200]|30|~~200~~|
|3|[400,50]|~~400~~|50|
|**4**|[30,20]|~~30~~|20|

Output: 110  
Explanation:   
The first person goes to city A for a cost of 10.
The second person goes to city A for a cost of 30.
The third person goes to city B for a cost of 50.
The fourth person goes to city B for a cost of 20.
The total minimum cost is 10 + 30 + 50 + 20 = 110 to have half the people interviewing in each city.

|Num| Data | Choice A|Choice B|Dif of A and B|  
|:---:|:--|:---:|:---:|:---: |
|1|[10,200]|10|~~200~~|190|
|2|[30,200]|30|~~200~~|170|
|3|[400,50]|~~400~~|50|350|
|**4**|[10,20]|~~10~~|20|10|

In [75]:
class Solution:
    def twoCitySchedCost(self, costs) -> int:
        diff = [costs[i][0]-costs[i][1] for i in range(len(costs))]
     
        # cost_new =sorted(costs,key =lambda x:diff[x])
        costs.sort(key=lambda x:diff[0])
        print(costs)
        result = 0 
        n = len(costs)//2
        for i in range(n):
            result = result+costs[i][0] + costs[i + n][1]
        return result
        

test = Solution()
testData = [[30,20],[10,20],[30,200],[400,50]]  
print(test.twoCitySchedCost(testData))

testData = [[10,20],[30,200],[400,50],[10,220]] #110
print(test.twoCitySchedCost(testData))

[[30, 20], [10, 20], [30, 200], [400, 50]]
290
[[10, 20], [30, 200], [400, 50], [10, 220]]
310


In [74]:
# Accept
class Solution:
    def twoCitySchedCost(self, costs) -> int:
        
        costs.sort(key = lambda x : x[0] - x[1])
        
        total = 0
        n = len(costs) // 2
        # costs [A, B] 
        for i in range(n):
            # Total = total + (A) + （B）
            total = total + costs[i][0] + costs[i + n][1]
        return total


test = Solution()
testData = [[10,20],[30,200],[400,50],[30,20]]  
print(test.twoCitySchedCost(testData))


testData = [[10,20],[30,200],[400,50],[10,220]] #110
print(test.twoCitySchedCost(testData))

110
110


### Using list.sort() and sorted()



In [45]:
A = [1,2,3,4,5,6]
B = ['A','p','p','l','e','s']
C = [6,5,4,1,2,3]
 
Z = zip(A,B)

# sorted
Z = sorted(Z,reverse=False)
print(Z,'\n')
Z = sorted(Z,reverse=True)
print(Z,'\n')

# list.sort()
Z.sort()
print(Z,'\n')
Z.sort(key= lambda x:x[0])
print(Z,'\n')
Z.sort(key= lambda x:x[1])
print(Z,'\n')


# unzip
A_new,B_new = zip(*Z)
print(A_new,'\n',B_new)



[(1, 'A'), (2, 'p'), (3, 'p'), (4, 'l'), (5, 'e'), (6, 's')] 

[(6, 's'), (5, 'e'), (4, 'l'), (3, 'p'), (2, 'p'), (1, 'A')] 

[(1, 'A'), (2, 'p'), (3, 'p'), (4, 'l'), (5, 'e'), (6, 's')] 

[(1, 'A'), (2, 'p'), (3, 'p'), (4, 'l'), (5, 'e'), (6, 's')] 

[(1, 'A'), (5, 'e'), (4, 'l'), (2, 'p'), (3, 'p'), (6, 's')] 

(1, 5, 4, 2, 3, 6) 
 ('A', 'e', 'l', 'p', 'p', 's')


In [73]:
import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[0,0,0]])
c = np.r_[a,b]
d = np.c_[a,b.T]
print('add row:\n',c,'\n')
print('add col:\n',d,'\n')

add row:
 [[1 2 3]
 [4 5 6]
 [7 8 9]
 [0 0 0]] 

add col:
 [[1 2 3 0]
 [4 5 6 0]
 [7 8 9 0]] 

